### ISSUE TITLE
DeepCoNN复现问题

### ISSUE THREAD

**Issue by npxiaoying** [TianHongTao/Recommendation-System-Graduation-Design#1]
作者你好，我跑了这个开源项目中的DeepCoNN模型，但是我跑出来的结果MSE是一直在增加的，不知道是不是我哪里跑错了，作者跑代码的过程中对应的MSE是多少呢？

**Comment by TianHongTao** [comment]
您好，本周之内我会将训练的具体参数和效果图po到这个issue下的。谢谢您的关注

**Comment by TianHongTao** [comment]
> 作者你好，我跑了这个开源项目中的DeepCoNN模型，但是我跑出来的结果MSE是一直在增加的，不知道是不是我哪里跑错了，作者跑代码的过程中对应的MSE是多少呢？
您好，本周之内我会将训练的具体参数和效果图po到这个issue下的。谢谢您的关注

**Comment by TianHongTao** [comment]
> 作者你好，我跑了这个开源项目中的DeepCoNN模型，但是我跑出来的结果MSE是一直在增加的，不知道是不是我哪里跑错了，作者跑代码的过程中对应的MSE是多少呢？

您好，本周之内我会将训练的具体参数和效果图po到这个issue下的。谢谢您的关注

**Comment by npxiaoying** [comment]
> > 作者你好，我跑了这个开源项目中的DeepCoNN模型，但是我跑出来的结果MSE是一直在增加的，不知道是不是我哪里跑错了，作者跑代码的过程中对应的MSE是多少呢？
> 
> 您好，本周之内我会将训练的具体参数和效果图po到这个issue下的。谢谢您的关注

我现在发现问题所在了.....你DeepCoNN复现的这个代码里的学习率设置错了，你的代码里torch.optim.Adam中，lr=LATENT_FACTOR_NUM，这样相当于把学习率设置成了64....,应该lr = LEARNING_RATE

**Comment by TianHongTao** [comment]
> > > 作者你好，我跑了这个开源项目中的DeepCoNN模型，但是我跑出来的结果MSE是一直在增加的，不知道是不是我哪里跑错了，作者跑代码的过程中对应的MSE是多少呢？
> > 
> > 
> > 您好，本周之内我会将训练的具体参数和效果图po到这个issue下的。谢谢您的关注
> 
> 我现在发现问题所在了.....你DeepCoNN复现的这个代码里的学习率设置错了，你的代码里torch.optim.Adam中，lr=LATENT_FACTOR_NUM，这样相当于把学习率设置成了64....,应该lr = LEARNING_RATE

好哒，可能是我的代码上传版本出了问题，我晚上回去给把新代码push上去，那这个issue我就关闭了～，卑微求个star👍

**Comment by TianHongTao** [comment]
![image](https://user-images.githubusercontent.com/27770413/82973234-78335000-a009-11ea-89ce-e4405a1b5c64.png)
