### ISSUE TITLE
AttributeError: 'Word2VecKeyedVectors' object has no attribute 'add'

### ISSUE THREAD

**Issue by duanchao** [TianHongTao/Recommendation-System-Graduation-Design#2]
你好，非常感谢你们在文本辅助推荐上做的大量工作并开源代码，我运行程序的时候一直报错，能否帮忙调试一下。
word_model  = Word2Vec.load(path.replace('.json', '.model'))
word_model.wv.add("<UNK/>", np.zeros(word_model.vector_size))

AttributeError: 'Word2VecKeyedVectors' object has no attribute 'add'

**Comment by TianHongTao** [comment]
您好，我这段代码的目的是补齐句子中 <UNK/> 和 <PAD/> 标识符所表示的无意义填充向量（使用 0 填充词向量）其产生如下：

```python
word_indices = [word_dict[w] if w in word_dict else word_dict["<UNK/>"] for w in sen]
sen += [ "<PAD/>"] * num_padding
```

由于使用的gensim版本可能有点落后，所以可能会出现
您可以通过检索：Word2VecKeyedVectors.add 或 'Word2VecKeyedVectors' object has no attribute 'add' 的query去查询相关问题（附带个看着还可以的链接）：
+ https://github.com/RaRe-Technologies/gensim/issues/2268

**Comment by TianHongTao** [comment]
![image](https://user-images.githubusercontent.com/27770413/84968688-b07e0800-b149-11ea-896e-9b794583be83.png)
具体的版本信息 **将于本周末** 提供于ReadMe文件， 祝好

**Comment by duanchao** [comment]
非常感谢你的及时回复，我再看看。&nbsp;

段超
华中师范大学
国家数字化学习工程技术研究中心


电 话：17771414406
邮 箱：870266923@qq.com
邮 编：430079
地 址：湖北省武汉市华中师范大学科学会堂509室




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "TianHongTao"<notifications@github.com&gt;; 
发送时间: 2020年6月18日(星期四) 上午9:55
收件人: "TianHongTao/ID-DAML"<ID-DAML@noreply.github.com&gt;; 
抄送: "红楼遗梦"<870266923@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [TianHongTao/ID-DAML] AttributeError: &#39;Word2VecKeyedVectors&#39; object has no attribute &#39;add&#39; (#2)





 

 具体的版本信息 将于本周末 提供于ReadMe文件， 祝好
