### ISSUE TITLE
DAML复现问题

### ISSUE THREAD

**Issue by QinghaoSun** [TianHongTao/Recommendation-System-Graduation-Design#6]
作者您好，我在尝试运行您的DAML代码过程中，出现了以下问题，想向您请教下解决方法。
Traceback (most recent call last):
  File "D:\ID-DAML-master\reappearance\DAML.py", line 412, in <module>
    main(path)
  File "D:\ID-DAML-master\reappearance\DAML.py", line 364, in main
    train_loss.backward()
  File "D:\anaconda3\envs\pytorch\lib\site-packages\torch\_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "D:\anaconda3\envs\pytorch\lib\site-packages\torch\autograd\__init__.py", line 175, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [24, 32]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

**Comment by TianHongTao** [comment]
![image](https://github.com/TianHongTao/ID-DAML/assets/27770413/96c88c04-6acf-4e11-ab15-ac5c72cbb09b)
你看看是不是这个问题

> 作者您好，我在尝试运行您的DAML代码过程中，出现了以下问题，想向您请教下解决方法。 Traceback (most recent call last): File "D:\ID-DAML-master\reappearance\DAML.py", line 412, in main(path) File "D:\ID-DAML-master\reappearance\DAML.py", line 364, in main train_loss.backward() File "D:\anaconda3\envs\pytorch\lib\site-packages\torch_tensor.py", line 396, in backward torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs) File "D:\anaconda3\envs\pytorch\lib\site-packages\torch\autograd__init__.py", line 175, in backward allow_unreachable=True, accumulate_grad=True) # Calls into the C++ engine to run the backward pass RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [24, 32]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

![image](https://github.com/TianHongTao/ID-DAML/assets/27770413/96c88c04-6acf-4e11-ab15-ac5c72cbb09b)
你看看是不是这个问题

**Comment by QinghaoSun** [comment]
谢谢作者，我改了一下发现问题并不在这里，问题主要是在这两行代码:
        #user_latent += u_ids
        user_latent = user_latent + u_ids
        #item_latent += i_ids
        item_latent = item_latent + i_ids
不能使用+=，网上的解释是：
![image](https://github.com/TianHongTao/ID-DAML/assets/132559148/97b2a321-59d3-45ab-972e-22bd09b0aa48)

**Comment by TianHongTao** [comment]
> [QinghaoSun](/QinghaoSun)
ok，我修改了
